### PR TITLE
Add a new way of using this module by skipping slow tests by default.

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Hello @zoul !

First thank you for this cool module :)

I wanted to use it but prefer to skip slow tests by default so instead of changing the default design I propose to add a new parameter when importing so we keep the old behaviour and add a new way of using your module.

I added also some tests and updated the doc.

Please review and merge if you consider it good for you :smiley: 

Best regards.

Thibault

### CODE REVIEW

**Comment by zoul** [comment]
Hi! Thank you very much for the contribution. It’s been ages since I last wrote a line of code in Perl. If you use the module, would you be interested in taking over the maintainership?

**Comment by thibaultduponchelle** [comment]
Ok why not :+1:

**Comment by thibaultduponchelle** [comment]
So according to https://www.cpan.org/modules/04pause.html#set-primary-maintainer I guess you have to "transfer maintainership" here : https://pause.perl.org/pause/authenquery?ACTION=share_perms (need to remember your CPAN password :smiley: )

And also tranfer github repo ownership (in repo settings at the end of the page)

Was it what you had in mind ?

**Comment by thibaultduponchelle** [comment]
Or another solution you can put me as a co-maintainer of the CPAN distribution and collaborator of the github repository.

Or something else ?

WDYT ?

**Comment by zoul** [comment]
Sorry, got caught in the corona storm. I’ve made you the primary maintainer of the module on CPAN. I tried to transfer the repo ownership on GitHub next, but the operation fails since you already have a fork of your own. Perhaps delete your fork from GitHub and I can transfer this one to you then? Thank you very much for taking over ❤️

**Comment by thibaultduponchelle** [comment]
I hope you're fine and your family too...

OK I deleted my fork.

> Thank you very much for taking over heart

You're welcome, it's a real pleasure ! :blush:

**Comment by zoul** [comment]
Woosh! And it’s your repo now! :) Good luck with the module.

**Comment by thibaultduponchelle** [comment]
Released to CPAN : https://metacpan.org/release/Test-Slow
:fireworks: :balloon: :tada:

**Pull request merged**
